  spring.datasource.url: jdbc:mysql://localhost:3306/user_registration
  spring.datasource.username: root
  spring.datasource.password: Admin@123
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.show-sql: true
  spring.jpa.properties.hibernate.format_sql: true
  spring.jpa.open-in-view: true
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

  #Hibernate properties
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  server.port: 8080


  spring:
    security:
      oauth2:
        client:
          registration:
            api-client-oidc:
              provider: spring
              client-id: api-client
              client-secret: secret
              authorization-grant-type: authorization_code
              redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
              scope: openid
              client-name: api-client-oidc
            api-client-authorization-code:
              provider: spring
              client-id: api-client
              client-secret: secret
              authorization-grant-type: authorization_code
              redirect-uri: "http://127.0.0.1:8080/authorized"
              scope: api.read
              client-name: api-client-authorization-code
          provider:
            spring:
              issuer-uri: http://DESKTOP-B1DPRDQ:9090